### ISSUE TITLE
[BUG] 과제 버그 

### ISSUE THREAD

**Issue by MokaRyua** [Science-assignment-reps-for-student/scarfs-front#205]
![image](https://user-images.githubusercontent.com/48910836/99274419-a7ff3a00-286d-11eb-9004-115d9a66ba7d.png)
과제가 존재하지 않을 때 과제 리스트로 리다이렉트 되는 않고 없는 내용으로 리다이렉트가 된다

**Comment by sema0710** [comment]
완료

**Comment by kangsinhee** [comment]
안고쳐졌음

**Comment by kangsinhee** [comment]
완료

**Comment by kangsinhee** [comment]
공지사항 페이지도 리다이렉트 확인 부탁해용~
