### ISSUE TITLE
PR 하고나서 브랜치좀 지워주세요

### ISSUE THREAD

**Issue by mallycrip** [Science-assignment-reps-for-student/scarfs-front#63]
브랜치 50개가 머농 ...

**Comment by mallycrip** [comment]
브랜치 재활용보다는 지운후 필요할 때마다 만드는게 좋을거 같은데 어떻게 생각하나요?

**Comment by woochanleee** [comment]
> 브랜치 재활용보다는 지운후 필요할 때마다 만드는게 좋을거 같은데 어떻게 생각하나요?

생각해볼 문제네용

**Comment by sema0710** [comment]
> > 브랜치 재활용보다는 지운후 필요할 때마다 만드는게 좋을거 같은데 어떻게 생각하나요?
> 
> 생각해볼 문제네용

저도 브랜치 네이밍 할때마다 겹치는게 많아서, 생각날 때 마다 머지 한 브랜치 지우고 있습니다.
@LeeSeongJinCa  @woochanleee  한번 생각해 봐야 할듯?

**Comment by mallycrip** [comment]
아니 브랜치 50개는 선넘었지 ㅋㅋㅋ
