### ISSUE TITLE
머지하는놈 정하세용

### ISSUE THREAD

**Issue by mallycrip** [Science-assignment-reps-for-student/scarfs-front#69]
ㅈㄱㄴ

**Comment by mallycrip** [comment]
pr 날린 사람이 머지하는 것보다는 매니저 한명을 정해서 하는게 좋을 것 같습니다 👍

**Comment by woochanleee** [comment]
> pr 날린 사람이 머지하는 것보다는 매니저 한명을 정해서 하는게 좋을 것 같습니다 👍

컨플릭트났을때 자기 코드는 자기가해야 편해유...
